language: d
sudo: false
install:
  - mkdir bin

matrix:
    include:
        - d: dmd-2.079.1
        - d: dmd-2.078.3
        - d: dmd-2.077.1
        - d: ldc-1.8.0
        - d: ldc-1.7.0
        - d: ldc-1.6.0

script:
  - dub test --build=unittest-cov --compiler=${DC}

after_success:
 - bash <(curl -s https://codecov.io/bash)
